version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ s3://tpm-main-site/ --region us-west-2
      # - aws cloudfront create-invalidation --distribution-id E24IXYQK3STXGH --paths "/*" --region us-west-2

artifacts:
  files: '**/*'
  name: MyViteApp